ARG IMAGE
FROM $IMAGE

ARG DOCKER_UID
ARG DOCKER_GID
ARG DOCKER_USERNAME
ARG HOST_TIMEZONE

ARG _DOCKER_BUILD_TEMP_ROOT_DIR="/docker_root_build_temp"
ARG _IMAGE_SETUP_SCRIPT="set_up_image.bash"

COPY $_IMAGE_SETUP_SCRIPT $_DOCKER_BUILD_TEMP_ROOT_DIR/
RUN bash $_DOCKER_BUILD_TEMP_ROOT_DIR/$_IMAGE_SETUP_SCRIPT \
$DOCKER_UID \
$DOCKER_GID \
$DOCKER_USERNAME \
$HOST_TIMEZONE
RUN rm -rf $_DOCKER_BUILD_TEMP_ROOT_DIR
