ARG IMAGE
FROM $IMAGE

ARG UID
ARG GID
ARG USERNAME
ARG HOST_TIMEZONE

ARG _DOCKER_BUILD_TEMP_ROOT_DIR="/docker_root_build_temp"
ARG _IMAGE_SETUP_SCRIPT="set_up_image.bash"

COPY $_IMAGE_SETUP_SCRIPT $_DOCKER_BUILD_TEMP_ROOT_DIR/
RUN bash $_DOCKER_BUILD_TEMP_ROOT_DIR/$_IMAGE_SETUP_SCRIPT \
$UID \
$GID \
$USERNAME \
$HOST_TIMEZONE
RUN rm -rf $_DOCKER_BUILD_TEMP_ROOT_DIR
