AccessModifierOffset: -2
AlignAfterOpenBracket: AlwaysBreak
AlignArrayOfStructures: None
AlignConsecutiveAssignments:
  AcrossComments: false
  AcrossEmptyLines: false
  AlignCompound: false
  Enabled: false
  PadOperators: false
AlignConsecutiveBitFields:
  AcrossComments: false
  AcrossEmptyLines: false
  AlignCompound: false
  Enabled: false
  PadOperators: false
AlignConsecutiveDeclarations:
  AcrossComments: false
  AcrossEmptyLines: false
  AlignCompound: false
  Enabled: false
  PadOperators: false
AlignConsecutiveMacros:
  AcrossComments: false
  AcrossEmptyLines: false
  AlignCompound: false
  Enabled: false
  PadOperators: false
AlignEscapedNewlines: DontAlign
AlignOperands: DontAlign
AlignTrailingComments: false
AllowAllArgumentsOnNextLine: false
AllowAllConstructorInitializersOnNextLine: false
AllowAllParametersOfDeclarationOnNextLine: false
AllowShortBlocksOnASingleLine: Never
AllowShortCaseLabelsOnASingleLine: false
AllowShortEnumsOnASingleLine: false
AllowShortFunctionsOnASingleLine: None
AllowShortIfStatementsOnASingleLine: Never
AllowShortLambdasOnASingleLine: None
AllowShortLoopsOnASingleLine: false
AlwaysBreakAfterDefinitionReturnType: None
AlwaysBreakAfterReturnType: None
AlwaysBreakBeforeMultilineStrings: true
AlwaysBreakTemplateDeclarations: Yes
AttributeMacros:
  - __example_placeholder
BasedOnStyle: LLVM
BinPackArguments: false
BinPackParameters: false
BitFieldColonSpacing: Both
BraceWrapping:
  AfterCaseLabel: true
  AfterClass: true
  AfterControlStatement: Always
  AfterEnum: true
  AfterExternBlock: true
  AfterFunction: true
  AfterNamespace: true
  AfterObjCDeclaration: true
  AfterStruct: true
  AfterUnion: true
  BeforeCatch: true
  BeforeElse: true
  BeforeLambdaBody: true
  BeforeWhile: true
  IndentBraces: false
  SplitEmptyFunction: true
  SplitEmptyNamespace: true
  SplitEmptyRecord: true
BreakAfterJavaFieldAnnotations: true
BreakBeforeBinaryOperators: None
BreakBeforeBraces: Custom
BreakBeforeConceptDeclarations: Always
BreakBeforeInheritanceComma: false
BreakBeforeTernaryOperators: true
BreakConstructorInitializers: BeforeColon
BreakConstructorInitializersBeforeComma: false
BreakInheritanceList: BeforeColon
BreakStringLiterals: false
ColumnLimit: 80
CommentPragmas: ^ example placeholder pragma1:.+$|^ example placeholder pragma2:.+$
CompactNamespaces: false
ConstructorInitializerAllOnOneLineOrOnePerLine: false
ConstructorInitializerIndentWidth: 2
ContinuationIndentWidth: 2
Cpp11BracedListStyle: true
DeriveLineEnding: false
DerivePointerAlignment: false
DisableFormat: false
EmptyLineAfterAccessModifier: Never
EmptyLineBeforeAccessModifier: LogicalBlock
ExperimentalAutoDetectBinPacking: false
FixNamespaceComments: false
ForEachMacros:
  - EXAMPLE_PLACEHOLDER_FOREACH
IfMacros:
  - EXAMPLE_PLACEHOLDER_IF
IncludeBlocks: Regroup
IncludeCategories:
  - CaseSensitive: true
    Priority: 300
    Regex: ^"external/.+"$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 300
    Regex: ^"third_party/.+"$|^"3rd_party/.+"$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 300
    Regex: ^"vendor/.+"$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 600
    Regex: ^<.+/.+\.h.?.?>$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 999
    Regex: ^<.+/.+>$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 500
    Regex: ^<.+\.h>$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 999
    Regex: ^<.+\..+>$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 400
    Regex: ^<.+>$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 200
    Regex: ^".+/.+\.h.?.?"$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 100
    Regex: ^".+\.h.?.?"$
    SortPriority: 0
  - CaseSensitive: true
    Priority: 999
    Regex: ^.+$
    SortPriority: 0
IncludeIsMainRegex: (_benchmark)?$|(_example)?$|(_test)?$
IncludeIsMainSourceRegex: ''
IndentAccessModifiers: false
IndentCaseBlocks: false
IndentCaseLabels: false
IndentExternBlock: NoIndent
IndentGotoLabels: true
IndentPPDirectives: None
IndentRequiresClause: false
IndentWidth: 2
IndentWrappedFunctionNames: true
InsertBraces: true
InsertTrailingCommas: None
JavaScriptQuotes: Double
JavaScriptWrapImports: true
KeepEmptyLinesAtTheStartOfBlocks: false
LambdaBodyIndentation: Signature
Language: Cpp
MacroBlockBegin: ^EXAMPLE_PLACEHOLDER_BEGIN1$|^EXAMPLE_PLACEHOLDER_BEGIN2$
MacroBlockEnd: ^EXAMPLE_PLACEHOLDER_END1$|^EXAMPLE_PLACEHOLDER_END2$
MaxEmptyLinesToKeep: 1
NamespaceIndentation: None
NamespaceMacros:
  - EXAMPLE_PLACEHOLDER_NAMESPACE
ObjCBinPackProtocolList: Never
ObjCBlockIndentWidth: 2
ObjCBreakBeforeNestedBlockParam: true
ObjCSpaceAfterProperty: false
ObjCSpaceBeforeProtocolList: false
PPIndentWidth: -1
PackConstructorInitializers: Never
PenaltyBreakAssignment: 2
PenaltyBreakBeforeFirstCallParameter: 19
PenaltyBreakComment: 300
PenaltyBreakFirstLessLess: 120
PenaltyBreakOpenParenthesis: 0
PenaltyBreakString: 1000
PenaltyBreakTemplateDeclaration: 10
PenaltyExcessCharacter: 1000000
PenaltyIndentedWhitespace: 0
PenaltyReturnTypeOnItsOwnLine: 60
PointerAlignment: Right
QualifierAlignment: Custom
QualifierOrder:
  - constexpr
  - inline
  - static
  - type
  - const
  - restrict
  - volatile
ReferenceAlignment: Pointer
ReflowComments: true
RemoveBracesLLVM: false
RequiresClausePosition: OwnLine
SeparateDefinitionBlocks: Always
ShortNamespaceLines: 0
SortIncludes: CaseSensitive
SortJavaStaticImport: Before
SortUsingDeclarations: true
SpaceAfterCStyleCast: false
SpaceAfterLogicalNot: false
SpaceAfterTemplateKeyword: false
SpaceAroundPointerQualifiers: Default
SpaceBeforeAssignmentOperators: true
SpaceBeforeCaseColon: false
SpaceBeforeCpp11BracedList: false
SpaceBeforeCtorInitializerColon: true
SpaceBeforeInheritanceColon: true
SpaceBeforeParens: Custom
SpaceBeforeParensOptions:
  AfterControlStatements: false
  AfterForeachMacros: false
  AfterFunctionDeclarationName: false
  AfterFunctionDefinitionName: false
  AfterIfMacros: false
  AfterOverloadedOperator: false
  AfterRequiresInClause: false
  AfterRequiresInExpression: false
  BeforeNonEmptyParentheses: false
SpaceBeforeRangeBasedForLoopColon: true
SpaceBeforeSquareBrackets: false
SpaceInEmptyBlock: false
SpaceInEmptyParentheses: false
SpacesBeforeTrailingComments: 1
SpacesInAngles: Never
SpacesInCStyleCastParentheses: false
SpacesInConditionalStatement: false
SpacesInContainerLiterals: false
SpacesInLineCommentPrefix:
  Maximum: 1
  Minimum: 1
SpacesInParentheses: false
SpacesInSquareBrackets: false
Standard: c++20
StatementAttributeLikeMacros:
  - EXAMPLE_PLACEHOLDER_STATEMENT_ATTRIBUTE
StatementMacros:
  - EXAMPLE_PLACEHOLDER_STATEMENT
TabWidth: 8
TypenameMacros:
  - EXAMPLE_PLACEHOLDER_TYPENAME
UseCRLF: false
UseTab: Never
WhitespaceSensitiveMacros:
  - EXAMPLE_PLACEHOLDER_WHITESPACE_SENSITIVE_MACRO
