apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-admin
  namespace: gitops-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitops-admin
    namespace: gitops-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-admin
  namespace: gitops-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/local/deploy
  prune: true
  retryInterval: 1m0s
  serviceAccountName: gitops-admin
  sourceRef:
    kind: GitRepository
    name: gitops-admin
    namespace: gitops-system
  timeout: 5m0s
  wait: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: gitops-infrastructure
  namespace: gitops-system
spec:
  interval: 1h0m0s
  path: ./k8s/clusters/local/deploy
  prune: true
  retryInterval: 1m0s
  serviceAccountName: gitops-admin
  sourceRef:
    kind: GitRepository
    name: gitops-infrastructure
    namespace: gitops-system
  timeout: 5m0s
  wait: false
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: gitops-admin
  namespace: gitops-system
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: gitops-admin
      namespace: gitops-system
  secretRef:
    name: gogs-webhook-secret
  type: generic-hmac
---
apiVersion: notification.toolkit.fluxcd.io/v1beta2
kind: Receiver
metadata:
  name: gitops-infrastructure
  namespace: gitops-system
spec:
  resources:
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: GitRepository
      name: gitops-infrastructure
      namespace: gitops-system
  secretRef:
    name: gogs-webhook-secret
  type: generic-hmac
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-admin
  namespace: gitops-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  secretRef:
    name: gitops-admin-gogs-ssh-key-lvnwoulc
  timeout: 1m0s
  url: ssh://git@git.localhost/wkaluza/personal_tools.git
  verify:
    mode: head
    secretRef:
      name: flux-git-gpg-sig-verification-gwnvmpi7
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: gitops-infrastructure
  namespace: gitops-system
spec:
  interval: 1h0m0s
  ref:
    branch: main
  secretRef:
    name: gitops-admin-gogs-ssh-key-lvnwoulc
  timeout: 1m0s
  url: ssh://git@git.localhost/wkaluza/infrastructure.git
  verify:
    mode: head
    secretRef:
      name: flux-git-gpg-sig-verification-gwnvmpi7
