apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  annotations:
    kyverno.io/kubernetes-version: "1.23"
    kyverno.io/kyverno-version: 1.6.2
    policies.kyverno.io/category: Flux
    policies.kyverno.io/description: This policy ensures that Flux GitRepository sources
      are pointed at a trusted repository.
    policies.kyverno.io/minversion: 1.6.0
    policies.kyverno.io/severity: medium
    policies.kyverno.io/subject: GitRepository
    policies.kyverno.io/title: Verify Flux Git Sources
  name: verify-flux-git-sources
spec:
  rules:
    - match:
        any:
          - resources:
              kinds:
                - GitRepository
      name: flux-git-repo-url
      validate:
        message: .spec.url must match ssh://git@git.localhost/wkaluza/?*.git
        pattern:
          spec:
            url: ssh://git@git.localhost/wkaluza/?*.git
  validationFailureAction: enforce
