health:
  storagedriver:
    enabled: true
    interval: 10s
    threshold: 3
http:
  addr: :5000
  headers:
    X-Content-Type-Options:
      - nosniff
log:
  fields:
    service: registry
proxy:
  remoteurl: https://registry-1.docker.io
storage:
  cache:
    blobdescriptor: inmemory
  filesystem:
    rootdirectory: /var/lib/registry
version: 0.1
