apiVersion: v1
kind: ServiceAccount
metadata:
  name: gitops-admin
  namespace: gitops-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gitops-admin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: gitops-admin
    namespace: gitops-system
